version: "2"
services:
  web:
    image: "nginx:1.19.5"
    container_name: "server"
    depends_on:
      - phpmyadmin
      - back
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
      - "./public:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    environment:
      NGINX_PORT: 80
  database:
    image: "mysql:8.0.22"
    container_name: "bbdd"
    env_file:
      - ./.env
    restart: always
    volumes:
      - "./database/mysql_data:/var/lib/mysql"
      - "./database/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
  phpmyadmin:
    image: "phpmyadmin:5.0.4-apache"
    container_name: "phpmyadmin"
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
  back:
    build: 
      args:
        user: api
        uid: 1000
      dockerfile: Dockerfile
      context: ./php-fpm
    container_name: "backend"
    ports:
      - "9000:9000"
    volumes:
      - "./api:/var/www"
    depends_on:
      - database